### PR TITLE
For NVC, accept regions from a file.

### PR DESCRIPTION
**Pull request by rsharris**
This adds the ability to specify regions from a file instead of one-by-one on the command line.  Assumed to be useful when the user has a *lot* of regions.

This might also warrant an addition in the xml file, presumably to make the new functionality available through galaxy.  Seems like the user would want to bind that to a set of intervals already in her galaxy space.  It wasn't immediately clear to me how to do that correctly.

### CODE REVIEW

**Comment by blankenberg** [comment]
Thanks for making this PR @rsharris! Definitely a worthwhile behavior. 

To make it fully useful in e.g. Galaxy, it should also accept an optional set of column numbers for the chrom name, start, and end, with the default being the standard bed configuration as is coded here. Often this is done using a single option with integer values separated by commas. Then it is just a matter of modifying the XML to have an optional input dataset.

**Comment by rsharris** [comment]
Can you point me at an example of column number specification "the galaxy way"?

I usually implement column numbers in my own stuff but wasn't sure what would be the "right" way to do it for this tool.  Often I allow an option that says "the first line is column names, use that to figure out the columns you need."  That didn't seem appropriate here though.

**Comment by blankenberg** [comment]
The GOPs tools are somewhat the canonical example of pulling column selections from a dataset's metadata, e.g. (strand not needed for this tool):
 - https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/gops/join/join.xml#L13
 - https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/gops/join/gops_join.py#L6

One thing in particular to be aware of is going from 1 based to 0 based column offsets.

**Comment by blankenberg** [comment]
xref https://github.com/blankenberg/nvc/commit/f34379dc24213fc663290a74d6b18ec7d5f96632

**Comment by blankenberg** [comment]
Change was merged into standalone NVC repository: https://github.com/blankenberg/nvc/commit/f34379dc24213fc663290a74d6b18ec7d5f96632

Thanks!

**Pull request closed without merging**
